services:
  - type: web
    name: bigray
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: bigray-db
          property: connectionString
      - key: PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK
        value: "true"
    healthCheckPath: /api/health

databases:
  - name: bigray-db
    plan: free
    databaseName: bigray
    user: bigray
